version: '2'
services:
    production:
        image: ms-todo:master
        ports:
          - "8080:8080"
        environment:
          - BEEGO_RUNMODE=prod
          - TODO_HOST=192.168.0.108
          - TODO_PORT=27017
        restart: always
