version: '2'
services:
    production:
        image: ms-todo:master
        ports:
          - "8080:8080"
        environment:
          - BEEGO_RUNMODE=prod
          - SAMPLES_DBHOST=192.168.0.108
          - SAMPLES_DBPORT=27017
        restart: always
